repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements

-   repo: https://github.com/pycqa/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --remove-unused-variables, --in-place]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=120]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            flake8-bugbear,
            flake8-docstrings,
            flake8-import-order,
            pep8-naming,
        ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            types-setuptools,
            numpy,
            pytest,
        ]

-   repo: https://github.com/jendrikseipp/vulture
    rev: v2.7
    hooks:
    -   id: vulture
        args: [zeroguess, tests, --min-confidence=80]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: ["-ll", "-r", "zeroguess", "tests", "examples"]

-   repo: https://github.com/pyupio/safety
    rev: 2.3.5
    hooks:
    -   id: safety
        args: ["check", "--full-report"] 