name: ZeroGuess Benchmarks

on:
  workflow_dispatch:  # Allow manual triggering
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'zeroguess/**'
  #     - 'examples/run_benchmark_*.py'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - 'zeroguess/**'
  #     - 'examples/run_benchmark_*.py'
  # schedule:
  #   - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight UTC

jobs:
  benchmark:
    name: Run ZeroGuess Benchmarks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.7'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest matplotlib pandas lmfit
        
    - name: Run benchmarks
      run: |
        cd examples
        python run_benchmark_1.py --function wavelet
        python run_benchmark_1.py --function double_gaussian

    - name: Archive benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: examples/benchmark_results
        retention-days: 90
        
    - name: Generate benchmark summary
      if: always()
      run: |
        # Create a benchmark directory structure
        mkdir -p benchmark_site/latest
        mkdir -p benchmark_site/history/$(date +%Y-%m-%d)
        
        # Copy results to the site directories
        cp -r examples/benchmark_results/* benchmark_site/latest/
        cp -r examples/benchmark_results/* benchmark_site/history/$(date +%Y-%m-%d)/
        
        # Create an index file
        echo "# ZeroGuess Benchmark Results" > benchmark_site/index.md
        echo "## Latest Results ($(date +%Y-%m-%d))" >> benchmark_site/index.md
        echo "- [Wavelet Function Report](latest/lmfit_comparison/wavelet/report.html)" >> benchmark_site/index.md
        echo "- [Double Gaussian Function Report](latest/lmfit_comparison/double_gaussian/report.html)" >> benchmark_site/index.md
        echo "## Historical Results" >> benchmark_site/index.md
        for dir in benchmark_site/history/*; do
          date=$(basename $dir)
          echo "- [$date](history/$date/)" >> benchmark_site/index.md
        done
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: benchmark_site
        branch: gh-pages
        clean: false  # Don't remove old files 