name: ZeroGuess Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black isort flake8 flake8-bugbear flake8-docstrings flake8-import-order pep8-naming mypy vulture
        pip install -e .
        
    - name: Check formatting with black
      run: |
        black --check zeroguess tests
        
    - name: Check import sorting with isort
      run: |
        isort --check zeroguess tests
        
    - name: Lint with flake8
      run: |
        flake8 zeroguess tests
        
    - name: Type check with mypy
      run: |
        mypy zeroguess
        
    - name: Check for unused code with vulture
      run: |
        vulture zeroguess tests --min-confidence=80 