name: ZeroGuess Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.7'
    
    - name: Check version consistency
      run: |
        # Extract version from pyproject.toml
        PYPROJECT_VERSION=$(grep -Po '(?<=version = ")[^"]*' pyproject.toml)
        echo "pyproject.toml version: $PYPROJECT_VERSION"
        
        # Extract version from __init__.py
        PACKAGE_VERSION=$(grep -Po '(?<=__version__ = ")[^"]*' zeroguess/__init__.py)
        echo "Package __version__: $PACKAGE_VERSION"
        
        # Check if versions match
        if [ "$PYPROJECT_VERSION" != "$PACKAGE_VERSION" ]; then
          echo "ERROR: Version mismatch! pyproject.toml has version $PYPROJECT_VERSION but package has version $PACKAGE_VERSION"
          echo "Please update the versions to match before releasing."
          exit 1
        fi
        
        echo "Version consistency check passed!"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build and package
      run: |
        python -m build
        
    - name: Check package
      run: |
        twine check dist/*
        
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: true 