name: ZeroGuess Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.7'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine python-dotenv
        # Install the package in development mode to make build.py work
        pip install -e .
        
    - name: Check version consistency
      run: |
        # Use build.py for version check
        python scripts/build.py --only-version-check
        
    - name: Build and package
      run: |
        python -m build
        
    - name: Check package
      run: |
        twine check dist/*
        
    - name: Publish package to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TESTPYPI_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
        verbose: true
        
    - name: Verify Test PyPI installation
      run: |
        # Wait a moment for the package to be available
        sleep 30
        
        # Create a temporary virtual environment
        python -m venv test_env
        source test_env/bin/activate
        
        # Try to install from Test PyPI
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple zeroguess
        
        # Verify installation
        python -c "import zeroguess; print(f'Successfully installed ZeroGuess {zeroguess.__version__} from Test PyPI')"
        
        # Clean up
        deactivate
        rm -rf test_env
        
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        skip-existing: true 