name: ZeroGuess Security Checks

# Workflow temporarily disabled
# Uncomment the section below to re-enable
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#   schedule:
#     # Run weekly security checks
#     - cron: '0 0 * * 0'

on:
  push:
    branches:
      - 'deactivate-security-checks'

jobs:
  security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit safety
        pip install -e .
        
    - name: Run bandit
      run: |
        bandit -r zeroguess tests examples -ll
        
    - name: Run safety
      run: |
        safety check
        
    - name: Check for vulnerable dependencies
      uses: pypa/gh-action-pip-audit@v1.0.8
      with:
        inputs: requirements.txt 